import { AiFillStar } from "react-icons/ai";




const data = [
  {
    img: 'https://images.asos-media.com/products/on-the-roger-advantage-trainers-in-all-white/24421180-1-allwhite?$n_640w$&wid=513&fit=constrain',
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(23 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  
  {
    img: "https://images.asos-media.com/products/adidas-originals-adimatic-gum-sole-trainers-in-black-and-white/203695013-1-black?$n_640w$&wid=634&fit=constrain",
    title: "Adidas adimatic gum",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£115",
    newPrice: "90",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://images.asos-media.com/products/adidas-originals-samba-og-trainers-in-black/205091962-1-black?$n_640w$&wid=634&fit=constrain",
    title: "Adidas Samba OG trainers",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(323 reviews)",
    prevPrice: "£85",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/adidas-originals-ozweego-trainers-in-triple-beige/203845842-1-beige?$n_640w$&wid=634&fit=constrain",
    title: "adidas Ozweego",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£99",
    newPrice: "90",
    company: "Adidas",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/adidas-originals-handball-spezial-gum-sole-trainers-in-ink-and-lime/205626924-1-multi?$n_640w$&wid=634&fit=constrain",
    title: "Handball Spezial",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },
  
  {
    img: "https://images.asos-media.com/products/adidas-originals-rivalry-low-trainers-in-white-and-green/205759967-1-multi?$n_640w$&wid=634&fit=constrain",
    title: "Nike Running Shoe",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/vans-sk8-hi-trainers-in-green-suede/203590902-1-khaki?$n_480w$&wid=476&fit=constrain",
    title: "sk8-hi suade",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£65",
    newPrice: "57",
    company: "Vans",
    color: "green",
    category: "flats",
  },

  {
    img: "https://images.asos-media.com/products/vans-hylane-chunky-trainers-in-white-with-gum-sole/206120984-1-white?$n_480w$&wid=476&fit=constrain",
    title: "Vans Hylane",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "67",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://images.asos-media.com/products/adidas-originals-samba-og-trainers-in-cream-and-black/206059666-1-multi?$n_640w$&wid=634&fit=constrain",
    title: "samba og Adidas",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "adidas",
    color: "white",
    category: "sneakers",
  },

  {
    img: "https://pbs.twimg.com/media/GOIo60vWwAA7Jit?format=jpg&name=medium",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://images.asos-media.com/products/puma-scend-running-trainers-in-green-white/204957254-1-green?$n_480w$&wid=476&fit=constrain",
    title: "PUMA scend",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£61",
    newPrice: "22",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/puma-velocity-nitro-3-trainers-in-pink/206349565-1-pink?$n_480w$&wid=476&fit=constrain",
    title: "Puma Velocity n3",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/puma-rs-x-efekt-trainers-in-black/204134036-1-black?$n_480w$&wid=476&fit=constrain",
    title: "puma rs-x Efekt",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "73",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/puma-mirage-sport-trainers-in-white-and-blue/205870676-1-whitegrey?$n_480w$&wid=476&fit=constrain",
    title: "puma mirage",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£83",
    newPrice: "71",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/puma-palermo-leather-trainers-in-black-and-white-black/205117227-1-blackwhite?$n_480w$&wid=476&fit=constrain",
    title: "Puma palermo",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://images.asos-media.com/products/puma-velophasis-trainers-in-grey/205432904-1-grey?$n_480w$&wid=476&fit=constrain",
    title: "puma velophasis",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "100",
    company: "Puma",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/vans-old-skool-trainers-in-rose-smoke/205062751-1-lightpink?$n_480w$&wid=476&fit=constrain",
    title: "Old Skool Rose",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "69",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    img: "https://images.asos-media.com/products/vans-old-skool-faux-leather-trainers-in-triple-white/204456624-1-white?$n_640w$&wid=634&fit=constrain",
    title: "Vans Old Skool",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(33 reviews)",
    prevPrice: "£85",
    newPrice: "75",
    company: "Vans",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/vans-classic-slip-on-trainers-in-blue-checkerboard/206119828-1-midblue?$n_640w$&wid=634&fit=constrain",
    title: "Unisex classic",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£65",
    newPrice: "45",
    company: "Vans",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/vans-old-skool-trainers-in-blue/206119808-1-midblue?$n_640w$&wid=634&fit=constrain",
    title: "old skul",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£65",
    newPrice: "50",
    company: "Vans",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/adidas-originals-sambae-trainers-in-white-and-red/205774678-1-multi?$n_480w$&wid=476&fit=constrain",
    title: "Adidas Sambae",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(12 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "Addidas",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://pbs.twimg.com/media/GM_t0pXWsAAIdXq?format=jpg&name=small",
    title: "Nike Retro Jordans iV",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  
  {
    img: "https://images.asos-media.com/products/adidas-originals-superstar-trainers-in-black/204992257-1-black?$n_640w$&wid=634&fit=constrain",
    title: "adidas superstar",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(103 reviews)",
    prevPrice: "£125",
    newPrice: "90",
    company: "adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://pbs.twimg.com/media/GKZ9KEHXIAATuYP?format=jpg&name=medium",
    title: "Air Jordan 1",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://pbs.twimg.com/media/GK0n8npX0AAwje3?format=jpg&name=small",
    title: "Air Jordan 5 Fire Red",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://pbs.twimg.com/media/GMCTEy4XUAA2rdo?format=jpg&name=small",
    title: "Nike Air Max 95 Neon",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "£85",
    newPrice: "20",
    company: "Nike",
    color: "grey",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/adidas-orignals-ozweego-trainers-in-black/203978596-1-black?$n_640w$&wid=634&fit=constrain",
    title: "adidas Ozweego",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(63 reviews)",
    prevPrice: "£99",
    newPrice: "90",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://images.asos-media.com/products/adidas-training-adilette-sliders-in-black/202260986-1-black?$n_640w$&wid=634&fit=constrain",
    title: "Adilette sliders",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(12 reviews)",
    prevPrice: "£85",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
];

export default data;